[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "queuer"
description = "A Discord bot for managing queues for on-interval events."
requires-python = ">=3.9"
license-files = ["LICENSE"]
readme = "README.md"

version = "0.1.0"

dependencies = [
  "discord.py>=2.6.0",
  "dotenv>=0.9.9",
  "aiosqlite>=0.20.0",
]

classifiers = [
  "Programming Language :: Python :: 3.9",
  "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]